-- gennaro-tedesco/nvim-peekup - Dynamically interact with vim registers.
-- tversteeg/registers.nvim - Non-obtrusive minimal preview of vim registers.
-- acksld/nvim-neoclip.lua - Clipboard manager Neovim plugin with telescope integration.
-- https://github.com/gbprod/yanky.nvim
