
        -- {
        --     "n", name = "neorg", {
        --       -- { 'n', '<leader>nd', ':Neorg workspace default_workspace<cr>', { noremap = true } },
        --       -- { 'n', '<leader>nn', ':Neorg workspace notes<cr>', options = { noremap = true } },
        --       -- { 'n', '<leader>nG', ':Neorg workspace gtd<cr>', options = { noremap = true } },
        --       -- { 'n', '<leader>nE', ':Neorg workspace example_gtd<cr>', options = { noremap = true } },
        --       -- { 'n', '<leader>ng', ':Neorg gtd ', options = { noremap = true } },
        --       -- { 'n', '<leader>nc', ':Neorg gtd capture<cr>', options = { noremap = true } },
        --       -- { 'n', '<leader>ne', ':Neorg gtd edit', options = { noremap = true } },
        --       -- { 'n', '<leader>nv', ':Neorg gtd views<cr>', options = { noremap = true } },
        --     }
        --   }, -- neorg -> move to leader > open > neorg
