-- https://github.com/fmorisan/vim-solnatspec
-- https://github.com/tomlion/vim-solidity
-- https://github.com/thesis/vim-solidity
-- https://github.com/qiuxiang/coc-solidity
-- https://github.com/0xHyoga/vimix-solidity
-- https://github.com/Rassska/Solidity-Vim-Colorschemes
