return {
  modules = {
    -- Language features
    ["annotations"] = true,        -- Code annotation generator
    ["auto_install"] = true,       -- Auto install LSP providers
    ["autopairs"] = true,          -- Automatically close character pairs
    ["comment"] = true,            -- Adds keybinds to comment in any language
    ["linter"] = true,             -- Linting and formatting for languages
    ["lsp"] = true,                -- Code completion
    ["snippets"] = true,           -- Code snippets for all languages

    -- Editor
    ["auto_session"] = true,       -- Remember sessions between loads
    ["colorizer"] = true,          -- Show colors in neovim
    ["editorconfig"] = true,       -- Support editorconfig files
    ["gitsigns"] = false,           -- Show git changes in sidebar
    ["illuminate"] = true,         -- Highlight other copies of the word you're hovering on
    ["indentlines"] = true,        -- Show indent lines with special characters
    ["range_highlight"] = true,    -- Highlight selected range from commands
    ["todo_comments"] = true,      -- Highlight TODO: comments
    ["doom_themes"] = true,     -- Extra themes for doom

    -- UI Components
    ["lsp_progress"] = true,       -- Check status of LSP loading
    ["tabline"] = true,            -- Tab bar buffer switcher
    ["dashboard"] = true,          -- A pretty dashboard upon opening
    ["trouble"] = true,         -- A pretty diagnostic viewer
    ["statusline"] = true,         -- A pretty status line at the bottom of the buffer
    ["minimap"] = true,         -- Shows current position in document
    ["terminal"] = true,        -- Integrated terminal in neovim
    ["symbols"] = true,         -- Navigate between code symbols using telescope
    ["ranger"] = true,          -- File explorer in neovim (TODO: Test)
    ["restclient"] = true,      -- Test HTTP requests from neovim (TODO: Test)
    ["show_registers"] = true,  -- Show and navigate between registers

    -- Tools
    ["dap"] = false,             -- Debug code through neovim
    ["explorer"] = true,           -- An enhanced filetree explorer
    ["firenvim"] = true,        -- Embed neovim in your browser
    ["lazygit"] = true,         -- Lazy git integration
    ["neogit"] = true,          -- A git client for neovim
    ["neorg"] = true,              -- Organise your life
    ["projects"] = true,           -- Quickly switch between projects
    ["superman"] = true,        -- Read unix man pages in neovim
    ["suda"] = false,            -- Save using sudo when necessary
    ["telescope"] = true,          -- Fuzzy searcher to find files, grep code and more
    ["whichkey"] = true,           -- An interactive sheet
  },
  langs = {
    -- Scripts
    ["lua"] = true,
    ["python"] = true,
    ["bash"] = true,

    -- Web
    ["javascript"] = true,
    ["typescript"] = true,
    ["css"] = true,
    ["vue"] = true,
    ["tailwindcss"] = true,

    -- Compiled
    ["rust"] = true,
    ["cc"] = true,

    -- JIT
    ["c_sharp"] = false,
    ["kotlin"] = false,
    ["java"] = false,

    ["config"] = true,          -- JSON, YAML, TOML
    ["markdown"] = true,
  },
  user = {
    ["ai"] = true,
    ["architext"] = true,
    ["async_jobs"] = false,
    ["audio"] = false,
    ["autocmds"] = false,
    ["awk"] = false,
    ["binds"] = true,
    ["binds_debug"] = false,
    ["binds_make_fn_under_cursor_into_bind"] = false,
    ["binds_mini_syntax"] = false,
    ["char_counter"] = false,
    ["clipboard"] = false,
    ["cmdline"] = true,
    ["code_outline"] = false,
    ["codeql"] = false,
    ["coderunner"] = false,
    ["collaborate"] = true,
    ["color_scheme_creation"] = false,
    ["color_schemes"] = true,
    ["colors"] = true,
    ["community_configs"] = false,
    ["competitive"] = false,
    ["complementree"] = false,
    ["create_cmds"] = false,
    ["create_module_sync_root"] = false,
    ["create_plugin"] = false,
    ["create_snippet"] = false,
    ["crypto"] = false,
    ["cursor"] = true,
    ["data_science"] = false,
    ["debugging"] = false,
    ["diagnostics"] = false,
    ["diagrams"] = false,
    ["dim_unused"] = false,
    ["docker"] = false,
    ["docs"] = true,
    ["doom_config_ui"] = false,
    ["doom_module_formatting"] = false,
    ["doom_queries_manager"] = false,
    ["doom_user_settings_ui"] = false,
    ["editing"] = true,
    ["fennel"] = false,
    ["figlet"] = false,
    ["file_explorers"] = false,
    ["filetype"] = false,
    ["flutter"] = false,
    ["folds"] = false,
    ["formatting"] = true,
    ["games"] = false,
    ["gdb"] = false,
    ["ghq"] = true,
    ["git_diffview"] = true,
    ["git_github"] = true,
    ["git_neogit"] = true,
    ["git_various"] = true,
    ["git_vgit"] = false,
    ["gitsigns"] = false,
    ["google_docs"] = false,
    ["gpg"] = true,
    ["haskell"] = false,
    ["help"] = false,
    ["highlighting"] = false,
    ["icons"] = false,
    ["images"] = false,
    ["increment"] = false,
    ["indent"] = false,
    ["kmonad"] = false,
    ["lang_nav"] = false,
    ["latex"] = false,
    ["legend"] = false,
    ["libmodal"] = false,
    ["litee"] = true,
    ["logging"] = false,
    ["lsp"] = false,
    ["lsp_semantinc_tokens"] = false,
    ["lsp_testing"] = false,
    ["lua_table_commands"] = false,
    ["mappings"] = false,
    ["markdown"] = false,
    ["marks"] = false,
    ["math_calculator"] = false,
    ["module_create_edit"] = false,
    ["module_disable"] = false,
    ["module_manager"] = false,
    ["module_merge"] = false,
    ["module_package_configs"] = false,
    ["module_package_toggle_fork"] = false,
    ["module_refactor_any_extra_vars_into_settings"] = false,
    ["module_remove"] = false,
    ["module_syntax_enforce"] = false,
    ["modules_edit"] = false,
    ["modules_move_component"] = false,
    ["monitor_mappings"] = false,
    ["motion"] = true,
    ["mouse"] = false,
    ["move"] = false,
    ["navigator"] = false,
    ["neorg"] = false,
    ["nodejs"] = false,
    ["nvim_luadev"] = false,
    ["nvim_queries"] = false,
    ["open_module_for_bind"] = false,
    ["pandoc"] = false,
    ["parse_module_cmd_args"] = false,
    ["paths"] = true,
    ["plugin_template"] = false,
    ["plugins_fork"] = false,
    ["plugins_local_reloader"] = false,
    ["printer"] = false,
    ["projects"] = false,
    ["quickfix"] = true,
    ["rayx"] = false,
    ["read_file"] = false,
    ["reaper_keys"] = false,
    ["refactor"] = true,
    ["refactor_fn_into_utils"] = false,
    ["regex"] = false,
    ["registers"] = false,
    ["remote_dev"] = false,
    ["rename"] = false,
    ["repl"] = false,
    ["repo_search"] = false,
    ["ripgrep"] = false,
    ["rust"] = false,
    ["scheme_formatting"] = false,
    ["scim"] = false,
    ["scroll"] = false,
    ["search_and_replace"] = true,
    ["session"] = false,
    ["snipets_create_edit"] = false,
    ["snippets"] = false,
    ["solidity"] = false,
    ["sort"] = false,
    ["spellcheck"] = false,
    ["ssh"] = false,
    ["startup"] = false,
    ["statusline"] = false,
    ["stenography"] = false,
    ["surround"] = false,
    ["tabs"] = false,
    ["tabular"] = false,
    ["telescope_doom_reloader"] = false,
    ["telescope_extensions"] = true,
    ["telescope_mappings_legend"] = false,
    ["terminal_integration"] = false,
    ["test"] = false,
    ["testing"] = false,
    ["tmux"] = false,
    ["todo"] = false,
    ["ts_context"] = false,
    ["ts_docs"] = false,
    ["ts_jump_2_func"] = false,
    ["ts_jump_to_module_part"] = false,
    ["ts_lang_detect"] = false,
    ["ts_mirror_doom_globals"] = false,
    ["ts_mode"] = false,
    ["ts_motions"] = false,
    ["ts_navigation"] = false,
    ["ts_playground"] = false,
    ["ts_plugins"] = false,
    ["ts_query_monitor"] = false,
    ["ts_rainbow"] = false,
    ["ts_refactor"] = false,
    ["ts_syntax"] = false,
    ["ts_testing"] = false,
    ["ts_testing_locals"] = false,
    ["ts_textobjects"] = false,
    ["ts_treehopper"] = false,
    ["ui"] = false,
    ["ui_pipeline"] = false,
    ["ui_toggle_components"] = false,
    ["undo"] = false,
    ["utilities"] = false,
    ["vigoux_templar"] = false,
    ["virtual_types"] = false,
    ["websearch"] = false,
    ["wildmenu"] = false,
    ["windows"] = true,
    ["wm"] = true,
  }
}

-- vim: sw=2 sts=2 ts=2 fdm=indent expandtab

